create table person(
                       id integer generated by default as identity primary key ,
                       name varchar unique not null ,
                       birth integer check ( birth>1800 and birth<3000 )
);

create table book(
                     id integer generated by default as identity primary key ,
                     title varchar not null,
                     author varchar not null,
                     year integer check ( year < 3000 ),
                     person_id integer references person(id) on delete set null,
                     taking_time timestamp
);